import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { generateDailyDraft, generateIdeas, generateWeeklyPlan, type ContentFormat } from "../contentAi";
import { calculateStreak, calculateWeeklyProgress } from "../consistency";
import * as db from "../db";
import { storagePut } from "../storage";
import { createVisualArchive } from "../visualExport";
import { renderCarouselSlide, renderProductPostCard, renderProductVisual, type ProductVisualMode, type VisualSlideDraft } from "../visuals";
import { generateProductSellingPackage } from "../productSellingPackage";
import { protectedProcedure, router } from "../_core/trpc";

const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const contentFormatSchema = z.enum(["caption", "carousel", "tip", "promo", "story"]);
const categorySchema = z.enum(["fashion", "accessories", "beauty", "personal_care", "other"]);
const visualTypeSchema = z.enum(["single_post", "carousel", "story"]);
const imageInput = z.object({ dataUrl: z.string().min(32).max(9_000_000), fileName: z.string().trim().min(1).max(120) });
const businessContextInput = z.object({ differentiator: z.string().trim().max(700).optional(), buyerHesitations: z.string().trim().max(700).optional(), firstTimeUnderstanding: z.string().trim().max(700).optional(), currentPriority: z.string().trim().max(500).optional(), neverSay: z.string().trim().max(700).optional() });
const businessProfileInput = z.object({ businessName: z.string().trim().min(2).max(160), businessType: z.string().trim().min(2).max(160), businessCategory: categorySchema.default("other"), targetAudience: z.string().trim().min(5).max(1000), customerMarket: z.string().trim().min(2).max(160).default("Nigeria"), contentPillars: z.array(z.string().trim().min(2).max(60)).min(2).max(6), postingGoal: z.string().trim().min(5).max(500), weeklyPostGoal: z.number().int().min(1).max(7), brandVoice: z.string().trim().min(2).max(160), brandPrimaryColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), brandAccentColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), defaultCta: z.string().trim().min(2).max(120).optional(), refreshFrom: dateSchema.optional() });

function profileContext(profile: NonNullable<Awaited<ReturnType<typeof db.getBusinessProfileByUserId>>>) { return { businessName: profile.businessName, businessType: profile.businessType, targetAudience: profile.targetAudience, customerMarket: profile.customerMarket || "Nigeria", contentPillars: JSON.parse(profile.contentPillars) as string[], postingGoal: profile.postingGoal, weeklyPostGoal: profile.weeklyPostGoal, brandVoice: profile.brandVoice, businessContext: parseBusinessContext(profile.businessContext) }; }
function parseStringArray(value: string | null) { try { const parsed = value ? JSON.parse(value) : []; return Array.isArray(parsed) && parsed.every(item => typeof item === "string") ? parsed : []; } catch { return []; } }
function parseBusinessContext(value: string | null) { try { const parsed = value ? JSON.parse(value) : {}; return parsed && typeof parsed === "object" ? parsed as z.infer<typeof businessContextInput> : {}; } catch { return {}; } }
function parseSlides(value: string | null): VisualSlideDraft[] { try { const parsed = value ? JSON.parse(value) : []; return Array.isArray(parsed) ? parsed.filter(slide => slide && typeof slide.heading === "string" && typeof slide.body === "string").map((slide, index) => ({ cardType: ["cover", "guide", "checklist", "comparison", "faq", "product", "closing"].includes(slide.cardType) ? slide.cardType : index === 0 ? "cover" : "guide", eyebrow: typeof slide.eyebrow === "string" ? slide.eyebrow : "ViraSquare guide", heading: slide.heading, body: slide.body, footer: typeof slide.footer === "string" ? slide.footer : "Save this for later", templateFamily: ["editorial", "action", "comparison", "explainer", "conversation"].includes(slide.templateFamily) ? slide.templateFamily : undefined, graphicCue: ["care", "warning", "choice", "fit", "budget", "process", "confidence", "quality", "style", "question", "none"].includes(slide.graphicCue) ? slide.graphicCue : undefined })) : []; } catch { return []; } }
function serializeItem(item: NonNullable<Awaited<ReturnType<typeof db.getContentItemById>>>) { return { ...item, hashtags: parseStringArray(item.hashtags), carouselSlides: parseSlides(item.carouselSlides) }; }
function requireProfile(profile: Awaited<ReturnType<typeof db.getBusinessProfileByUserId>>) { if (!profile?.isOnboarded) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Complete your business profile before generating content." }); return profile; }
function productContext(product: NonNullable<Awaited<ReturnType<typeof db.getProductById>>>) { return { id: product.id, name: product.name, price: product.price, currency: product.currency, productCategory: product.productCategory, bestFor: product.bestFor, choiceReasons: product.choiceReasons, buyerNote: product.buyerNote, categoryDetails: product.categoryDetails, details: product.details }; }

function decodeUpload(dataUrl: string) {
  const match = dataUrl.match(/^data:(image\/(?:png|jpe?g|webp));base64,([A-Za-z0-9+/=]+)$/);
  if (!match) throw new TRPCError({ code: "BAD_REQUEST", message: "Upload a PNG, JPEG, or WebP image." });
  const mimeType = match[1];
  const buffer = Buffer.from(match[2], "base64");
  if (buffer.length > 5 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Choose an image smaller than 5 MB." });
  return { buffer, mimeType };
}

function safeFileName(value: string) { return value.replace(/[^a-zA-Z0-9._-]/g, "-").replace(/-+/g, "-").slice(0, 90) || "product-image"; }
function brandFrom(profile: NonNullable<Awaited<ReturnType<typeof db.getBusinessProfileByUserId>>>) { return { businessName: profile.businessName, businessType: profile.businessType, brandVoice: profile.brandVoice, primaryColor: profile.brandPrimaryColor, accentColor: profile.brandAccentColor, defaultCta: profile.defaultCta, brandLogoKey: profile.brandLogoKey, instagramHandle: profile.instagramHandle, closingSignature: profile.closingSignature }; }

function productVisualSource(product: NonNullable<Awaited<ReturnType<typeof db.getProductWithMedia>>>) { return { name: product.name, price: product.price, currency: product.currency, details: product.details, imageKey: product.imageKey, productCategory: product.productCategory, bestFor: product.bestFor, choiceReasons: product.choiceReasons, buyerNote: product.buyerNote, categoryDetails: product.categoryDetails }; }

async function makeVisual(ctx: { user: { id: number } }, input: { type: "single_post" | "carousel" | "story"; itemId: number; productId?: number; visualMode?: ProductVisualMode }) {
  const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id));
  const item = await db.getContentItemById(ctx.user.id, input.itemId);
  if (!item?.caption) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Create the written post first, then ViraSquare can make the visual." });
  if (input.visualMode === "stylish" && input.type !== "single_post") throw new TRPCError({ code: "BAD_REQUEST", message: "Stylish generation is available only for a single real-product post." });
  const resolvedProductId = input.productId ?? item.productId ?? undefined;
  const product = resolvedProductId ? await db.getProductWithMedia(ctx.user.id, resolvedProductId) : undefined;
  if (resolvedProductId && !product) throw new TRPCError({ code: "NOT_FOUND", message: "That product is unavailable." });
  if (item.requiresProduct && !product) throw new TRPCError({ code: "PRECONDITION_FAILED", message: item.preparationNote || "This post needs a real product image and verified details before it can be made." });
  const visualMode = input.visualMode || "standard";
  const deliverable = await db.createVisualDeliverable({ userId: ctx.user.id, contentItemId: item.id, productId: product?.id, type: input.type, title: item.title, aspectRatio: input.type === "story" ? "9:16" : "4:5", generationMode: visualMode, status: "generating" });
  try {
    const brand = brandFrom(profile);
    const productSource = product ? productVisualSource(product) : undefined;
    if (input.type === "single_post") {
      if (!productSource) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Choose a real product to make a trustworthy product visual." });
      const visual = await renderProductPostCard({ brand, product: productSource, mode: visualMode });
      await db.replaceVisualSlides(deliverable.id, [{ slideNumber: 1, heading: productSource.name, body: productSource.bestFor || productSource.choiceReasons || productSource.details || item.caption, eyebrow: visualMode === "stylish" ? "STYLED PRODUCT VISUAL" : "REAL PRODUCT POST", footer: brand.defaultCta || "Send us a message to order.", cardType: "product", sourceMode: visual.sourceMode, assetKey: visual.assetKey, assetUrl: visual.assetUrl }]);
    } else if (input.type === "story") {
      if (!productSource) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Choose a real product to make a trustworthy product visual." });
      const visual = await renderProductVisual({ brand, product: productSource, heading: item.title, supporting: item.caption });
      await db.replaceVisualSlides(deliverable.id, [{ slideNumber: 1, heading: item.title, body: item.caption, sourceMode: visual.sourceMode, assetKey: visual.assetKey, assetUrl: visual.assetUrl }]);
    } else {
      const drafts = parseSlides(item.carouselSlides);
      const slides = (drafts.length ? drafts : [{ cardType: "cover" as const, eyebrow: brand.businessName, heading: item.title, body: item.caption, footer: brand.defaultCta || "Save this for later" }]).slice(0, 6);
      const postTemplateFamily = drafts[0]?.templateFamily;
      const rendered = await Promise.all(slides.map((draft, index) => renderCarouselSlide({ brand, draft, slideNumber: index + 1, totalSlides: slides.length, product: productSource, useProduct: Boolean(productSource && draft.cardType === "product"), postTemplateFamily })));
      await db.replaceVisualSlides(deliverable.id, rendered.map((visual, index) => ({ slideNumber: index + 1, heading: slides[index].heading, body: slides[index].body, eyebrow: slides[index].eyebrow, footer: slides[index].footer, cardType: slides[index].cardType, sourceMode: visual.sourceMode, assetKey: visual.assetKey, assetUrl: visual.assetUrl })));
    }
    await db.updateVisualDeliverableStatus(ctx.user.id, deliverable.id, "ready");
    await db.updateContentLifecycle(ctx.user.id, item.id, "generated");
    await db.recordContentActivity({ userId: ctx.user.id, contentItemId: item.id, deliverableId: deliverable.id, eventType: "generated", metadata: JSON.stringify({ type: input.type, productId: product?.id ?? null, visualMode, source: input.type === "single_post" ? "openai_product_visual" : "card_engine" }) });
    const saved = await db.getVisualDeliverableById(ctx.user.id, deliverable.id);
    if (!saved) throw new Error("The visual could not be reloaded.");
    return saved;
  } catch (error) {
    await db.updateVisualDeliverableStatus(ctx.user.id, deliverable.id, "failed");
    throw error;
  }
}

export const viraSquareRouter = router({
  profile: protectedProcedure.query(async ({ ctx }) => { const profile = await db.getBusinessProfileByUserId(ctx.user.id); return profile ? { ...profile, contentPillars: parseStringArray(profile.contentPillars), businessContext: parseBusinessContext(profile.businessContext) } : null; }),
  workspace: protectedProcedure.input(z.object({ today: dateSchema, weekStart: dateSchema, weekEnd: dateSchema })).query(async ({ ctx, input }) => { const profile = await db.getBusinessProfileByUserId(ctx.user.id); if (!profile?.isOnboarded) return { profile: null, todayContent: null, weeklyPlan: [], productCount: 0, consistency: { streak: 0, weeklyProgress: 0, totalCompleted: 0 } }; const [todayContent, weeklyPlan, completedDates, productCount] = await Promise.all([db.getContentItemForDate(ctx.user.id, input.today), db.getContentItemsForRange(ctx.user.id, input.weekStart, input.weekEnd), db.getCompletedContentDates(ctx.user.id), db.countProductsByUserId(ctx.user.id)]); const completedThisWeek = weeklyPlan.filter(item => item.status === "completed").length; return { profile: { ...profile, contentPillars: parseStringArray(profile.contentPillars), businessContext: parseBusinessContext(profile.businessContext) }, todayContent: todayContent ? serializeItem(todayContent) : null, weeklyPlan: weeklyPlan.map(item => ({ ...item, hashtags: parseStringArray(item.hashtags), carouselSlides: parseSlides(item.carouselSlides) })), productCount, consistency: { streak: calculateStreak(completedDates, input.today), weeklyProgress: calculateWeeklyProgress(completedThisWeek, profile.weeklyPostGoal), totalCompleted: new Set(completedDates).size } }; }),
  saveProfile: protectedProcedure.input(businessProfileInput).mutation(async ({ ctx, input }) => { const { refreshFrom, ...profileInput } = input; const profile = await db.upsertBusinessProfile({ ...profileInput, userId: ctx.user.id, contentPillars: JSON.stringify(profileInput.contentPillars), isOnboarded: true }); let refreshedToday = null; if (refreshFrom) { await db.removePlannedContentFromDate(ctx.user.id, refreshFrom); const recent = await db.getRecentContentItems(ctx.user.id); const draft = await generateDailyDraft(profileContext(profile), refreshFrom, undefined, recent.map(item => item.title)); const item = await db.createContentItem({ userId: ctx.user.id, profileId: profile.id, plannedFor: refreshFrom, ...draft, hashtags: JSON.stringify(draft.hashtags), carouselSlides: JSON.stringify(draft.carouselSlides), status: "planned" }); refreshedToday = serializeItem(item); } return { ...profile, contentPillars: parseStringArray(profile.contentPillars), refreshedToday }; }),
  saveBusinessContext: protectedProcedure.input(businessContextInput).mutation(async ({ ctx, input }) => { const saved = await db.updateBusinessContext(ctx.user.id, JSON.stringify(input), "completed"); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "Your business profile could not be found." }); return { ...saved, contentPillars: parseStringArray(saved.contentPillars), businessContext: parseBusinessContext(saved.businessContext) }; }),
  dismissBusinessContext: protectedProcedure.mutation(async ({ ctx }) => { const saved = await db.updateBusinessContext(ctx.user.id, "", "dismissed"); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "Your business profile could not be found." }); return { success: true } as const; }),
  setProductInviteStatus: protectedProcedure.input(z.object({ status: z.enum(["dismissed", "completed"]) })).mutation(async ({ ctx, input }) => { const saved = await db.updateProductInviteStatus(ctx.user.id, input.status); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "Your business profile could not be found." }); return { success: true } as const; }),
  saveBrandIdentity: protectedProcedure.input(z.object({ instagramHandle: z.string().trim().max(80).optional(), closingSignature: z.string().trim().max(140).optional(), logo: imageInput.optional() })).mutation(async ({ ctx, input }) => { let brandLogoKey: string | null | undefined; let brandLogoUrl: string | null | undefined; if (input.logo) { const { buffer, mimeType } = decodeUpload(input.logo.dataUrl); const upload = await storagePut(`${ctx.user.id}/brand/${Date.now()}-${safeFileName(input.logo.fileName)}`, buffer, mimeType); brandLogoKey = upload.key; brandLogoUrl = upload.url; } const saved = await db.updateBrandIdentity(ctx.user.id, { instagramHandle: input.instagramHandle ? input.instagramHandle.replace(/^@+/, "") : null, closingSignature: input.closingSignature || null, brandLogoKey, brandLogoUrl }); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "Your business profile could not be found." }); return { ...saved, contentPillars: parseStringArray(saved.contentPillars), businessContext: parseBusinessContext(saved.businessContext) }; }),
  products: protectedProcedure.query(({ ctx }) => db.listProductsByUserId(ctx.user.id)),
  productUsage: protectedProcedure.query(({ ctx }) => db.getProductUsage(ctx.user.id)),
  product: protectedProcedure.input(z.object({ productId: z.number().int().positive() })).query(({ ctx, input }) => db.getProductWithMedia(ctx.user.id, input.productId)),
  createProduct: protectedProcedure.input(z.object({ name: z.string().trim().min(2).max(180), price: z.string().trim().max(80).optional(), currency: z.string().trim().min(2).max(12).default("NGN"), details: z.string().trim().max(800).optional(), productCategory: z.string().trim().max(100).optional(), bestFor: z.string().trim().max(320).optional(), choiceReasons: z.string().trim().max(1600).optional(), buyerNote: z.string().trim().max(500).optional(), categoryDetails: z.string().trim().max(1600).optional(), image: imageInput })).mutation(async ({ ctx, input }) => { const { buffer, mimeType } = decodeUpload(input.image.dataUrl); const upload = await storagePut(`${ctx.user.id}/products/${Date.now()}-${safeFileName(input.image.fileName)}`, buffer, mimeType); const product = await db.createProduct({ userId: ctx.user.id, name: input.name, price: input.price || null, currency: input.currency, details: input.details || null, productCategory: input.productCategory || null, bestFor: input.bestFor || null, choiceReasons: input.choiceReasons || null, buyerNote: input.buyerNote || null, categoryDetails: input.categoryDetails || null, imageKey: upload.key, imageUrl: upload.url }); await db.addProductMedia({ productId: product.id, role: "primary", sortOrder: 0, storageKey: upload.key, url: upload.url, mimeType }); await db.updateProductInviteStatus(ctx.user.id, "completed"); return product; }),
  addProductMedia: protectedProcedure.input(z.object({ productId: z.number().int().positive(), image: imageInput })).mutation(async ({ ctx, input }) => { const product = await db.getProductById(ctx.user.id, input.productId); if (!product) throw new TRPCError({ code: "NOT_FOUND", message: "That product is unavailable." }); const { buffer, mimeType } = decodeUpload(input.image.dataUrl); const upload = await storagePut(`${ctx.user.id}/products/${product.id}-${Date.now()}-${safeFileName(input.image.fileName)}`, buffer, mimeType); const existing = await db.listProductMedia(product.id); return db.addProductMedia({ productId: product.id, role: "gallery", sortOrder: existing.length, storageKey: upload.key, url: upload.url, mimeType }); }),
  updateProduct: protectedProcedure.input(z.object({ productId: z.number().int().positive(), name: z.string().trim().min(2).max(180), price: z.string().trim().max(80).optional(), currency: z.string().trim().min(2).max(12).default("NGN"), details: z.string().trim().max(800).optional(), productCategory: z.string().trim().max(100).optional(), bestFor: z.string().trim().max(320).optional(), choiceReasons: z.string().trim().max(1600).optional(), buyerNote: z.string().trim().max(500).optional(), categoryDetails: z.string().trim().max(1600).optional() })).mutation(async ({ ctx, input }) => { const saved = await db.updateProduct(ctx.user.id, input.productId, { name: input.name, price: input.price || null, currency: input.currency, details: input.details || null, productCategory: input.productCategory || null, bestFor: input.bestFor || null, choiceReasons: input.choiceReasons || null, buyerNote: input.buyerNote || null, categoryDetails: input.categoryDetails || null }); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "That product is unavailable." }); return saved; }),
  deleteProduct: protectedProcedure.input(z.object({ productId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const product = await db.getProductById(ctx.user.id, input.productId); if (!product) throw new TRPCError({ code: "NOT_FOUND", message: "That product is unavailable." }); await db.deleteProduct(ctx.user.id, input.productId); return { success: true } as const; }),
  generateDaily: protectedProcedure.input(z.object({ date: dateSchema })).mutation(async ({ ctx, input }) => { const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id)); const [existing, recent] = await Promise.all([db.getContentItemForDate(ctx.user.id, input.date), db.getRecentContentItems(ctx.user.id)]); const draft = await generateDailyDraft(profileContext(profile), input.date, existing ? { title: existing.title, objective: existing.objective, format: existing.format as ContentFormat, brief: existing.brief } : undefined, recent.filter(item => item.id !== existing?.id).map(item => item.title)); const updates = { ...draft, hashtags: JSON.stringify(draft.hashtags), carouselSlides: JSON.stringify(draft.carouselSlides) }; const item = existing ? await db.updateGeneratedContent(ctx.user.id, existing.id, updates) : await db.createContentItem({ userId: ctx.user.id, profileId: profile.id, plannedFor: input.date, ...updates, status: "planned" }); if (!item) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Your content could not be saved." }); return serializeItem(item); }),
  generateIdeas: protectedProcedure.input(z.object({ format: contentFormatSchema.optional(), objective: z.string().trim().min(2).max(100).optional(), topic: z.string().trim().min(2).max(240).optional(), productId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id)); const isProductLed = input.objective === "Feature a product" || input.format === "promo"; if (isProductLed && !input.productId) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Choose or add a product before generating product-led ideas." }); const selectedProduct = input.productId ? await db.getProductById(ctx.user.id, input.productId) : undefined; if (input.productId && !selectedProduct) throw new TRPCError({ code: "NOT_FOUND", message: "That product is unavailable." }); const recent = await db.getRecentContentItems(ctx.user.id); return generateIdeas(profileContext(profile), input.format, recent.map(item => item.title), { objective: input.objective, topic: input.topic, selectedProduct: selectedProduct ? productContext(selectedProduct) : undefined }); }),
  saveIdea: protectedProcedure.input(z.object({ date: dateSchema, title: z.string().min(2).max(300), objective: z.string().min(2).max(120), format: contentFormatSchema, brief: z.string().min(5).max(2000), productId: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id)); const item = await db.replaceContentForDate({ userId: ctx.user.id, profileId: profile.id, plannedFor: input.date, title: input.title, objective: input.objective, format: input.format, brief: input.brief, productId: input.productId ?? null, requiresProduct: Boolean(input.productId), preparationNote: input.productId ? "Use the saved product image and the facts you supplied for this product." : null, status: "planned" }); return serializeItem(item); }),
  generateContent: protectedProcedure.input(z.object({ itemId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id)); const item = await db.getContentItemById(ctx.user.id, input.itemId); if (!item) throw new TRPCError({ code: "NOT_FOUND", message: "That content item was not found." }); const selectedProduct = item.productId ? await db.getProductById(ctx.user.id, item.productId) : undefined; if (item.requiresProduct && !selectedProduct) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Choose or add the product this post is about before making its rich content." }); const draft = await generateDailyDraft(profileContext(profile), item.plannedFor, { title: item.title, objective: item.objective, format: item.format as ContentFormat, brief: item.brief }, [], selectedProduct ? productContext(selectedProduct) : undefined); const saved = await db.updateGeneratedContent(ctx.user.id, item.id, { ...draft, hashtags: JSON.stringify(draft.hashtags), carouselSlides: JSON.stringify(draft.carouselSlides) }); if (!saved) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Your generated content could not be saved." }); await db.recordContentActivity({ userId: ctx.user.id, contentItemId: item.id, eventType: "generated", metadata: JSON.stringify({ source: "content", productId: item.productId ?? null }) }); return serializeItem(saved); }),
  makeVisual: protectedProcedure.input(z.object({ itemId: z.number().int().positive(), productId: z.number().int().positive().optional(), type: visualTypeSchema, visualMode: z.enum(["standard", "stylish"]).optional() })).mutation(({ ctx, input }) => makeVisual(ctx, input)),
  regenerateVisualSlide: protectedProcedure.input(z.object({ deliverableId: z.number().int().positive(), slideNumber: z.number().int().positive(), correction: z.string().trim().min(3).max(420).optional() })).mutation(async ({ ctx, input }) => { const deliverable = await db.getVisualDeliverableById(ctx.user.id, input.deliverableId); if (!deliverable) throw new TRPCError({ code: "NOT_FOUND", message: "That visual is unavailable." }); const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id)); const slide = deliverable.slides.find(item => item.slideNumber === input.slideNumber); if (!slide) throw new TRPCError({ code: "NOT_FOUND", message: "That slide is unavailable." }); const product = deliverable.productId ? await db.getProductWithMedia(ctx.user.id, deliverable.productId) : undefined; if (deliverable.type === "single_post" && product) { const visual = await renderProductPostCard({ brand: brandFrom(profile), product: productVisualSource(product), mode: deliverable.generationMode, correction: input.correction }); await db.updateVisualSlideAsset(deliverable.id, slide.slideNumber, { assetKey: visual.assetKey, assetUrl: visual.assetUrl, sourceMode: visual.sourceMode, heading: product.name, body: product.bestFor || product.choiceReasons || product.details || slide.body, eyebrow: deliverable.generationMode === "stylish" ? "STYLED PRODUCT FLYER" : "PRODUCT FLYER", footer: profile.defaultCta, cardType: "product" }); const saved = await db.getVisualDeliverableById(ctx.user.id, deliverable.id); if (!saved) throw new Error("The updated product visual could not be loaded."); return saved; } const sourceItem = deliverable.contentItemId ? await db.getContentItemById(ctx.user.id, deliverable.contentItemId) : undefined; const sourceDrafts = sourceItem ? parseSlides(sourceItem.carouselSlides) : []; const sourceDraft = sourceDrafts[input.slideNumber - 1]; const productSource = product ? productVisualSource(product) : undefined; const draft: VisualSlideDraft = sourceDraft || { cardType: slide.cardType, eyebrow: slide.eyebrow || profile.businessName, heading: slide.heading, body: slide.body || "", footer: slide.footer || profile.defaultCta }; const visual = await renderCarouselSlide({ brand: brandFrom(profile), draft, slideNumber: slide.slideNumber, totalSlides: deliverable.slides.length, product: productSource, useProduct: Boolean(productSource && draft.cardType === "product"), postTemplateFamily: sourceDrafts[0]?.templateFamily || draft.templateFamily }); await db.updateVisualSlideAsset(deliverable.id, slide.slideNumber, { assetKey: visual.assetKey, assetUrl: visual.assetUrl, sourceMode: visual.sourceMode, heading: draft.heading, body: draft.body, eyebrow: draft.eyebrow, footer: draft.footer, cardType: draft.cardType }); const saved = await db.getVisualDeliverableById(ctx.user.id, deliverable.id); if (!saved) throw new Error("The updated slide could not be loaded."); return saved; }),
  exportVisualSet: protectedProcedure.input(z.object({ deliverableId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const deliverable = await db.getVisualDeliverableById(ctx.user.id, input.deliverableId); if (!deliverable) throw new TRPCError({ code: "NOT_FOUND", message: "That visual is unavailable." }); if (deliverable.status !== "ready") throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Wait for the visual set to finish before downloading it." }); const archive = await createVisualArchive({ userId: ctx.user.id, title: deliverable.title, slides: deliverable.slides }); if (deliverable.contentItemId) { await db.updateContentLifecycle(ctx.user.id, deliverable.contentItemId, "downloaded"); await db.recordContentActivity({ userId: ctx.user.id, contentItemId: deliverable.contentItemId, deliverableId: deliverable.id, eventType: "downloaded", metadata: JSON.stringify({ slideCount: archive.slideCount }) }); } return archive; }),
  productSellingPackage: protectedProcedure.input(z.object({ deliverableId: z.number().int().positive() })).query(({ ctx, input }) => db.getProductSellingPackage(ctx.user.id, input.deliverableId)),
  generateProductSellingPackage: protectedProcedure.input(z.object({ deliverableId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const deliverable = await db.getVisualDeliverableById(ctx.user.id, input.deliverableId); if (!deliverable || deliverable.type !== "single_post" || deliverable.status !== "ready" || !deliverable.productId) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Finish a ready product flyer before preparing its selling package." }); const existing = await db.getProductSellingPackage(ctx.user.id, deliverable.id); if (existing) return existing; const [profile, product] = await Promise.all([db.getBusinessProfileByUserId(ctx.user.id), db.getProductById(ctx.user.id, deliverable.productId)]); const readyProfile = requireProfile(profile); if (!product) throw new TRPCError({ code: "NOT_FOUND", message: "The product for this flyer is unavailable." }); const sellingPackage = await generateProductSellingPackage({ brand: { businessName: readyProfile.businessName, businessType: readyProfile.businessType, customerMarket: readyProfile.customerMarket, brandVoice: readyProfile.brandVoice, defaultCta: readyProfile.defaultCta, instagramHandle: readyProfile.instagramHandle }, product: productContext(product) }); return db.upsertProductSellingPackage({ userId: ctx.user.id, deliverableId: deliverable.id, productId: product.id, ...sellingPackage }); }),
  visuals: protectedProcedure.query(({ ctx }) => db.listVisualDeliverablesByUserId(ctx.user.id)),
  library: protectedProcedure.query(({ ctx }) => db.listContentLibrary(ctx.user.id)),
  activity: protectedProcedure.query(({ ctx }) => db.listContentActivity(ctx.user.id)),
  preparationReminder: protectedProcedure.input(z.object({ date: dateSchema })).query(async ({ ctx, input }) => { const tomorrow = new Date(`${input.date}T12:00:00`); tomorrow.setDate(tomorrow.getDate() + 1); const nextDate = tomorrow.toISOString().slice(0, 10); const item = await db.getContentItemForDate(ctx.user.id, nextDate); return item?.requiresProduct ? { item: serializeItem(item), date: nextDate, note: item.preparationNote || "Tomorrow’s post needs a real product image and verified details." } : null; }),
  setLifecycle: protectedProcedure.input(z.object({ itemId: z.number().int().positive(), lifecycleStatus: z.enum(["reviewed", "posted", "archived"]), outcome: z.enum(["not_set", "conversations", "orders", "engagement", "saved_for_later"]).optional(), note: z.string().trim().max(600).optional() })).mutation(async ({ ctx, input }) => { const saved = await db.updateContentLifecycle(ctx.user.id, input.itemId, input.lifecycleStatus, { outcome: input.outcome, note: input.note }); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "That content item was not found." }); await db.recordContentActivity({ userId: ctx.user.id, contentItemId: saved.id, eventType: input.lifecycleStatus === "posted" ? "posted" : input.lifecycleStatus === "archived" ? "archived" : "reviewed", metadata: JSON.stringify({ outcome: input.outcome || "not_set" }) }); return serializeItem(saved); }),
  generateWeeklyPlan: protectedProcedure.input(z.object({ dates: z.array(dateSchema).length(7) })).mutation(async ({ ctx, input }) => { const profile = requireProfile(await db.getBusinessProfileByUserId(ctx.user.id)); const [existing, recent] = await Promise.all([db.getContentItemsForRange(ctx.user.id, input.dates[0], input.dates[6]), db.getRecentContentItems(ctx.user.id)]); const generated = await generateWeeklyPlan(profileContext(profile), input.dates, recent.map(item => item.title)); await Promise.all(generated.plan.filter(item => item.isPostDay && input.dates.includes(item.date) && !existing.some(saved => saved.plannedFor === item.date)).map(item => db.createContentItem({ userId: ctx.user.id, profileId: profile.id, plannedFor: item.date, title: item.title, objective: item.objective, format: item.format, brief: item.brief, status: "planned" }))); const saved = await db.getContentItemsForRange(ctx.user.id, input.dates[0], input.dates[6]); return saved.map(item => ({ ...item, hashtags: parseStringArray(item.hashtags), carouselSlides: parseSlides(item.carouselSlides) })); }),
  setCompletion: protectedProcedure.input(z.object({ itemId: z.number().int().positive(), completed: z.boolean() })).mutation(async ({ ctx, input }) => { const saved = await db.setContentCompletion(ctx.user.id, input.itemId, input.completed); if (!saved) throw new TRPCError({ code: "NOT_FOUND", message: "That content item was not found." }); return serializeItem(saved); }),
});
