import { Resvg } from "@resvg/resvg-js";
import { storageGetSignedUrl, storagePut } from "./storage";

type Brand = { businessName: string; businessType: string; brandVoice: string; primaryColor?: string; accentColor?: string; defaultCta?: string };
type ProductSource = { name: string; price: string | null; currency: string; details: string | null; imageKey: string };
export type VisualSlideDraft = { cardType: "cover" | "guide" | "checklist" | "comparison" | "faq" | "product" | "closing"; eyebrow: string; heading: string; body: string; footer: string };
export type RenderedVisual = { assetKey: string; assetUrl: string; sourceMode: "product" | "generated" | "template" };

function escapeXml(value: string) { return value.replace(/[<>&'"]/g, character => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[character] ?? character); }
function short(value: string, length: number) { return value.length > length ? `${value.slice(0, Math.max(0, length - 1)).trim()}…` : value; }
function wrap(value: string, max = 27, limit = 4) { const rows: string[] = []; let row = ""; for (const word of short(value, 370).split(/\s+/)) { const next = row ? `${row} ${word}` : word; if (next.length > max && row) { rows.push(row); row = word; } else row = next; } if (row) rows.push(row); return rows.slice(0, limit); }
function rows(lines: string[], x: number, y: number, size: number, color: string, weight = 700, line = 1.08) { return lines.map((item, index) => `<text x="${x}" y="${y + index * size * line}" font-family="Georgia, serif" font-size="${size}" font-weight="${weight}" fill="${color}">${escapeXml(item)}</text>`).join(""); }
function bodyLines(value: string) { return wrap(value.replace(/[•]/g, " "), 43, 5); }
function key(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 70) || "visual"; }

async function dataUriFromKey(storageKey: string) { const url = await storageGetSignedUrl(storageKey); const response = await fetch(url); if (!response.ok) throw new Error("The product image could not be read from storage."); const buffer = Buffer.from(await response.arrayBuffer()); const mime = response.headers.get("content-type")?.split(";")[0] || "image/jpeg"; return `data:${mime};base64,${buffer.toString("base64")}`; }
async function renderSvg(svg: string, keyPrefix: string): Promise<RenderedVisual> { const png = new Resvg(svg, { fitTo: { mode: "width", value: 1080 } }).render().asPng(); const { key: storedKey, url } = await storagePut(`visuals/${keyPrefix}.png`, png, "image/png"); return { assetKey: storedKey, assetUrl: url, sourceMode: "template" }; }
function imageBlock(imageData: string, x: number, y: number, width: number, height: number, radius = 46) { const clipId = `clip-${Math.random().toString(36).slice(2, 9)}`; return `<defs><clipPath id="${clipId}"><rect x="${x}" y="${y}" width="${width}" height="${height}" rx="${radius}" /></clipPath></defs><rect x="${x}" y="${y}" width="${width}" height="${height}" rx="${radius}" fill="#e5ece0"/><image href="${imageData}" x="${x}" y="${y}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid meet" clip-path="url(#${clipId})"/>`; }

function palette(brand: Brand) { return { ink: brand.primaryColor || "#263327", accent: brand.accentColor || "#EAF2CA", soft: "#F7F7F2", paper: "#FFFEFA", mist: "#DCE8D5", sage: "#75965F" }; }
function richCardSvg({ brand, draft, number, total }: { brand: Brand; draft: VisualSlideDraft; number: number; total: number }) {
  const colors = palette(brand); const title = wrap(draft.heading, 24, 4); const text = bodyLines(draft.body); const footer = short(draft.footer || brand.defaultCta || "Save this for later.", 72); const badge = draft.cardType === "checklist" ? "✓" : draft.cardType === "faq" ? "?" : draft.cardType === "comparison" ? "↔" : draft.cardType === "closing" ? "→" : draft.cardType === "cover" ? "✦" : "•";
  const lineStart = draft.cardType === "checklist" ? 760 : 820;
  const detail = draft.cardType === "checklist" ? text.slice(0, 4).map((item, i) => `<circle cx="144" cy="${lineStart + i * 82 - 11}" r="16" fill="${colors.accent}"/><text x="144" y="${lineStart + i * 82 - 3}" text-anchor="middle" font-family="Arial, sans-serif" font-size="20" font-weight="700" fill="${colors.ink}">✓</text><text x="184" y="${lineStart + i * 82}" font-family="Arial, sans-serif" font-size="28" fill="#5D6A5D">${escapeXml(item)}</text>`).join("") : rows(text, 120, lineStart, 31, "#5D6A5D", 400, 1.35);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" fill="${colors.soft}"/><rect x="58" y="58" width="964" height="1234" rx="58" fill="${colors.paper}"/><circle cx="910" cy="145" r="190" fill="${colors.accent}" opacity=".92"/><path d="M78 1060 C260 920, 420 1210, 610 1050 S 890 900, 1010 1080" fill="none" stroke="${colors.mist}" stroke-width="42" opacity=".85"/><text x="120" y="146" font-family="Arial, sans-serif" font-size="22" font-weight="700" letter-spacing="3" fill="${colors.sage}">${escapeXml((draft.eyebrow || brand.businessName).toUpperCase())}</text><text x="960" y="146" text-anchor="end" font-family="Arial, sans-serif" font-size="21" font-weight="700" fill="#70816F">${number}/${total}</text><rect x="120" y="210" width="86" height="86" rx="25" fill="${colors.ink}"/><text x="163" y="268" text-anchor="middle" font-family="Georgia, serif" font-size="48" fill="${colors.accent}">${badge}</text>${rows(title, 120, 410, draft.cardType === "cover" ? 72 : 61, colors.ink)}<rect x="120" y="${draft.cardType === "checklist" ? 675 : 700}" width="840" height="1" fill="${colors.mist}"/>${detail}<rect x="120" y="1170" width="840" height="1" fill="${colors.mist}"/><text x="120" y="1230" font-family="Arial, sans-serif" font-size="23" font-weight="700" fill="${colors.sage}">${escapeXml(footer.toUpperCase())}</text><text x="960" y="1230" text-anchor="end" font-family="Arial, sans-serif" font-size="20" font-weight="700" fill="#718071">${escapeXml(brand.businessName)}</text></svg>`;
}

export function buildRichCardSvg(brand: Brand, draft: VisualSlideDraft, slideNumber = 1, totalSlides = 1) {
  return richCardSvg({ brand, draft, number: slideNumber, total: totalSlides });
}
function productSvg({ brand, product, image, draft, number, total }: { brand: Brand; product: ProductSource; image: string; draft: VisualSlideDraft; number: number; total: number }) { const colors = palette(brand); const title = wrap(draft.heading, 22); const price = product.price ? `${product.currency === "NGN" ? "₦" : `${product.currency} `}${product.price}` : "Ask for today’s price"; return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" fill="${colors.soft}"/><circle cx="970" cy="145" r="230" fill="${colors.accent}" opacity=".72"/><text x="82" y="90" font-family="Arial, sans-serif" font-size="23" font-weight="700" letter-spacing="3" fill="${colors.sage}">${escapeXml((draft.eyebrow || brand.businessName).toUpperCase())}</text><text x="998" y="90" text-anchor="end" font-family="Arial, sans-serif" font-size="20" font-weight="700" fill="#70816F">${number}/${total}</text>${imageBlock(image, 82, 150, 916, 570)}<rect x="82" y="770" width="916" height="456" rx="48" fill="${colors.ink}"/>${rows(title, 130, 870, 59, "#FFFEFA")}<text x="130" y="${870 + title.length * 65 + 30}" font-family="Arial, sans-serif" font-size="27" fill="#D5E3CF">${escapeXml(short(draft.body || product.details || "A thoughtful choice for your everyday needs.", 120))}</text><line x1="130" y1="1132" x2="950" y2="1132" stroke="#ffffff" stroke-opacity=".20"/><text x="130" y="1195" font-family="Arial, sans-serif" font-size="38" font-weight="700" fill="${colors.accent}">${escapeXml(price)}</text><text x="950" y="1194" text-anchor="end" font-family="Arial, sans-serif" font-size="22" font-weight="700" fill="#ffffff">${escapeXml((draft.footer || brand.defaultCta || "Send us a message to order.").toUpperCase())}</text></svg>`; }

export async function renderProductVisual({ brand, product, heading, supporting }: { brand: Brand; product: ProductSource; heading: string; supporting: string }) { const image = await dataUriFromKey(product.imageKey); const draft: VisualSlideDraft = { cardType: "product", eyebrow: brand.businessName, heading, body: supporting, footer: brand.defaultCta || "Send us a message to order." }; const visual = await renderSvg(productSvg({ brand, product, image, draft, number: 1, total: 1 }), `product-${Date.now()}`); return { ...visual, sourceMode: "product" as const }; }
export async function renderCarouselSlide({ brand, draft, slideNumber, totalSlides, product, useProduct }: { brand: Brand; draft: VisualSlideDraft; slideNumber: number; totalSlides: number; product?: ProductSource; useProduct?: boolean }) { if (product && useProduct && draft.cardType === "product") { const image = await dataUriFromKey(product.imageKey); const visual = await renderSvg(productSvg({ brand, product, image, draft, number: slideNumber, total: totalSlides }), `card-product-${Date.now()}-${slideNumber}`); return { ...visual, sourceMode: "product" as const }; } return renderSvg(buildRichCardSvg(brand, draft, slideNumber, totalSlides), `card-${key(draft.cardType)}-${Date.now()}-${slideNumber}`); }
