import { ArrowRight, CheckCircle2, Sparkles } from "lucide-react";

export function GlowOilIllustration({ dark = false }: { dark?: boolean }) {
  return <svg viewBox="0 0 120 144" className="h-full w-full" aria-hidden="true"><rect width="120" height="144" rx="18" fill={dark ? "#0B1220" : "#EFF6FF"}/><ellipse cx="60" cy="124" rx="32" ry="6" fill={dark ? "#ffffff" : "#0B1220"} opacity=".14"/><rect x="38" y="27" width="44" height="82" rx="10" fill="#E48C64"/><rect x="46" y="17" width="28" height="18" rx="6" fill="#321A2A"/><rect x="45" y="52" width="30" height="28" rx="3" fill="#FCEBDD"/><text x="60" y="65" textAnchor="middle" fontSize="8" fontWeight="700" fill="#321A2A">NURA</text><text x="60" y="75" textAnchor="middle" fontSize="5" fill="#321A2A">GLOW OIL</text></svg>;
}

export function ContentFormatPreview({ kind }: { kind: "product" | "education" | "trust" }) {
  if (kind === "education") return <div className="relative h-[148px] overflow-hidden rounded-xl bg-[#EFF6FF] p-3"><p className="text-[8px] font-bold tracking-[.12em] text-[#2563EB]">ILLUSTRATIVE FORMAT</p><div className="mt-6 flex items-end gap-2">{["Purpose", "Routine", "Use it"].map((label, index) => <div key={label} className="flex h-20 flex-1 flex-col justify-between rounded-lg border border-white bg-white p-2 shadow-sm" style={{ transform: `translateY(${index === 1 ? -8 : 0}px)` }}><span className="text-[8px] font-bold text-[#2563EB]">0{index + 1}</span><span className="font-serif text-[11px] leading-3 text-[#0B1220]">{label}</span></div>)}</div></div>;
  if (kind === "trust") return <div className="relative h-[148px] overflow-hidden rounded-xl border border-[#DCE6F2] bg-white p-3"><span className="absolute right-3 top-3 grid h-7 w-7 place-items-center rounded-full bg-[#EFF6FF] text-[#2563EB]"><CheckCircle2 className="h-4 w-4" /></span><p className="text-[8px] font-bold tracking-[.12em] text-[#2563EB]">ILLUSTRATIVE FORMAT</p><div className="mt-4 flex items-center gap-3"><div className="h-16 w-16 rounded-xl bg-[#0B1220] p-1"><GlowOilIllustration dark /></div><p className="max-w-[11rem] font-serif text-lg leading-tight text-[#0B1220]">What customers should know before they choose.</p></div><div className="mt-3 flex gap-1"><span className="h-1.5 w-12 rounded-full bg-[#2563EB]" /><span className="h-1.5 w-7 rounded-full bg-[#BFDBFE]" /></div></div>;
  return <div className="relative h-[148px] overflow-hidden rounded-xl bg-[#0B1220] p-3 text-white"><span className="absolute -right-5 -top-5 h-20 w-20 rounded-full border-[13px] border-[#E48C64]" /><p className="relative text-[8px] font-bold tracking-[.12em] text-[#BFDBFE]">ILLUSTRATIVE FORMAT</p><div className="relative mt-3 flex items-center gap-3"><div className="h-16 w-16 rounded-xl bg-white/10 p-1"><GlowOilIllustration dark /></div><div><p className="font-serif text-lg leading-none">Glow in your everyday.</p><p className="mt-2 text-[9px] text-[#BFDBFE]">Product post</p></div></div><div className="relative mt-3 flex justify-end"><span className="rounded bg-[#E48C64] px-2 py-1 text-[9px] font-bold text-[#321A2A]">₦8,500</span></div></div>;
}

export function ContentSystemGraphic() {
  return <div className="relative mx-auto h-60 w-full max-w-[360px]" aria-label="Illustrative ViraSquare content system"><div className="absolute left-12 top-0 h-48 w-48 rounded-full border-[18px] border-white/10" /><div className="absolute left-0 top-7 w-44 rounded-2xl border border-white/20 bg-[#0B1220] p-3 text-white shadow-xl"><p className="text-[8px] font-bold tracking-[.13em] text-[#93C5FD]">DIRECTION</p><p className="mt-3 font-serif text-xl leading-none">Build trust today.</p><div className="mt-4 flex gap-1"><span className="h-1.5 w-10 rounded-full bg-[#2563EB]" /><span className="h-1.5 w-6 rounded-full bg-white/30" /></div></div><div className="absolute right-0 top-14 w-48 rounded-2xl border border-white bg-white p-3 text-[#0B1220] shadow-xl"><div className="flex items-center justify-between"><p className="text-[8px] font-bold tracking-[.13em] text-[#2563EB]">READY VISUAL</p><Sparkles className="h-3.5 w-3.5 text-[#2563EB]" /></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#EFF6FF] p-2"><div className="h-12 w-12 rounded-lg bg-[#0B1220] p-1"><GlowOilIllustration dark /></div><p className="font-serif text-sm leading-4">Ready to share.</p></div></div><div className="absolute bottom-0 left-12 w-48 rounded-2xl border border-white/30 bg-[#BFDBFE] p-3 text-[#0B1220] shadow-xl"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white text-[#2563EB]"><ArrowRight className="h-3.5 w-3.5" /></span><div><p className="text-[8px] font-bold tracking-[.13em] text-[#1D4ED8]">BUYER REPLY</p><p className="mt-1 text-[10px] font-semibold">A helpful next response.</p></div></div></div></div>;
}
